# DOCKER-VERSION 0.8.1

from ubuntu:12.04

run apt-get update
run apt-get -y install openjdk-7-jre-headless && apt-get clean

env JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/jre
env PATH $JAVA_HOME:/bin:$PATH
